url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Yuchen BAI" # the name of your site, e.g. ACME Corp.
description: "A 3nd year PhD student within Statify in Inria Grenoble & AMAP Lab."
