menu:
- {name: 'Publications', url: '/publications'}
- {name: 'Teaching', url: '/courses'}
- {name: 'CV', url: '/cv'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}

courses:
- {name: 'INF101', url: '2022-2023_INF101_UGA'}

social:
- {icon: 'github', link: 'https://github.com/Na1an'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/yuchen-bai-4aa318ba/'}
- {icon: 'twitter', link: 'https://github.com/Na1an'}
- {icon: 'instagram', link: 'https://github.com/Na1an'}

contacts:
- {name: 'Yuchen BAI', title: 'PhD student', department: 'ED MSTII', institution: 'Grenoble Alpes University', institution_address: 'Grenoble, France', email: 'yuchen.bai@inria.fr', image: 'assets/img/contact.jpg'}
